### ISSUE TITLE
Completion for subsequent arg erroneously returns completions of previous arg

### ISSUE THREAD

**Issue by cspotcode** [yargs/yargs#1277]
I noticed a quirk in the completion logic.  Given this (contrived) subcommand structure:

`my-cli-tool foo food`

If I type `my-cli-tool foo` and then press tab, it'll complete `foo` into `food`.  This is incorrect because `food` is not a valid top-level command; it's nested.  `food` should only be offered if I've pressed space *after* typing `foo`.  yargs can detect this because it'll be passed an additional empty string in argv.

For example, if I don't press space, argv is:
`[ 'my-cli-tool', 'foo' ]`
If I do press space, argv is:
`[ 'my-cli-tool', 'foo', '' ]`

**Comment by trevorlinton** [comment]
@cspotcode can you confirm this is fixed in the latest version of yargs (13.2.1)?

**Comment by cspotcode** [comment]
@trevorlinton this is not fixed; here's a reproduction.

https://runkit.com/embed/x4dvsjw12u7a/

**Comment by cspotcode** [comment]
Has there been any update on this?
