### ISSUE TITLE
offset demand of a subcommand

### ISSUE THREAD

**Issue by gajus** [yargs/yargs#353]
I have an entry file:

```js
#! /usr/bin/env node

import yargs, {
    argv
} from 'yargs';

import {
    fixCommand,
    lintCommand
} from './commands';

yargs
    .help('help')
    .strict()
    .command('fix', 'Fix code format.', fixCommand)
    .command('lint', 'Report code format errors.', lintCommand)
    .argv;
```

My `lintCommand.js` looks like this:

```js
export default (yargs) => {
    let argv;

    argv = yargs
        .help('help')
        .strict()
        .options({
            stdin: {
                default: false,
                describe: 'Used to indicate that subject body will be read from stdin.',
                type: 'boolean'
            }
        })
        .argv;

    if (argv.stdin) {
        // Require no argv._ values.
        yargs
            .demand(0, 0)
            .argv;
    } else {
        // Require at least one argv._ value.
        yargs
            .demand(1)
            .argv;
    }
};

```

When I execute the program such as:

```sh
node ./index.js lint --stdin
```

I get an error:

> Too many non-option arguments: got 1, maximum of 0

The reason for this is that `argv._` value is `[ 'lint' ]`.

How do I remove the command value from `argv._`?

**Comment by nexdrew** [comment]
@gajus Interesting problem. Does something like this work for `lintCommand.js`?

```js
export default (yargs, parentArgv) => {
    yargs
        .help('help')
        .strict()
        .options({
            stdin: {
                default: false,
                describe: 'Used to indicate that subject body will be read from stdin.',
                type: 'boolean'
            }
        });

    if (parentArgv.stdin) {
        // Require no argv._ values.
        yargs.demand(0, 0);
    } else {
        // Require at least one argv._ value.
        yargs.demand(1);
    }

    let argv = yargs.argv;
};
```

**Comment by gajus** [comment]
How would that help? `argv._` is still `['lint']`.

**Comment by gajus** [comment]
Here is how I did it:

```js
import yargs from 'yargs';

export default () => {
    let argv;

    argv = yargs(process.argv.splice(3))
        .help('help')
        .strict()
        .argv;

    console.log('argv._', argv._);
};
```

```sh
node ./index.js lint --stdin foo
> argv._ [ 'best' ]
```

**Comment by bcoe** [comment]
@gajus we've been undertaking a big overhaul of commands. We've introduced the concept of required positional arguments, which I think will solve this problem for you partially:

https://github.com/bcoe/yargs/pull/368

Eventually we could introduce the concept of positional arguments that accept multiple values: `<foo...>` which I think would completely solve this problem you're running into in an elegant way.

**Comment by bcoe** [comment]
@gajus could you give the new commands API a spin:

`npm i yargs@next`

I think you'll find the new API, specifically positional arguments, help solve some of the issues that you've run into:

https://github.com/bcoe/yargs/blob/4.x/README.md#commandcmd-desc-builder-handler

**Comment by nexdrew** [comment]
The problem with `.demand()` offsets has been fixed with #582, which will be in the upcoming 5.0.0 release. 🎉 

Otherwise, there are now a few different ways to accomplish "conditional" demand validation, either using optional positional args as bcoe suggested or even parsing, checking `argv.stdin`, resetting and reparsing within the builder function.

**Comment by bcoe** [comment]
@gajus we've released #582 to `next` \o/

To give it a spin run:

`npm cache clear; npm i yargs@next`

Please feel free to reopen this ticket with an update, if @nexdrew and my tips along with #582 don't do the trick for you.

**Comment by gajus** [comment]
@bcoe I am still getting a variation of this issue.

This time the setup is:

```js
// ./index.js
#!/usr/bin/env node

import yargs from 'yargs';

// eslint-disable-next-line no-unused-expressions
yargs
  .env()
  .strict()
  .commandDir('commands')
  .help()
  .wrap(null)
  .argv;
```

```js
// ./commands/update-cinemas.js

export const builder = (yargs) => {
  yargs
    .usage('Usage: showtime-data-management-program update-cinemas <files ...>')
    .options({
      ...commandLineConnectionOptionsShape
    })
    .demand(1);
};

export const handler = (argv) => {
  const scraperPaths = argv._;

  console.log('argv', argv);
};
```

and I am executing the program as:

```sh
babel-node ./src/bin update-cinemas foo
```

The `argv._` results in:

```
[
  'update-cinemas',
  'foo'
]
```

while I would expect it to result in `['foo']`.

**Comment by bcoe** [comment]
@gajus the module for `update-cinemas.js` should look something like this:

```js
'use strict'
exports.command = 'update-cinemas <files...>'
exports.desc = 'showtime-data-management-program update-cinema'

exports.builder = function (yargs) {
  yargs
    .options({
      ...commandLineConnectionOptionsShape
    })
}

exports.handler = function (argv) {
// do stuff with argv.
}
```

We have documentation here: https://github.com/yargs/yargs#providing-a-command-module
but I think the README file in general is getting a bit unwieldy.

Assuming this solution does the trick for you, I'd love your feedback on https://github.com/yargs/yargs/issues/694, regarding how we can cleanup our documentation.

**Comment by gajus** [comment]
> We have documentation here: https://github.com/yargs/yargs#providing-a-command-module
but I think the README file in general is getting a bit unwieldy.
Got it. The missing bit was `export const command = 'update-cinemas <files ...>';`. That did the trick. Thank you.

**Comment by gajus** [comment]
Oh! I thought `<files...>` is just a documentation fragment. I didn't realise it captures the values into `argv._.files`. To be fair, thats clear from the docs now that I read through it again.

I was trying to get the `<files...>` in `argv._`.
