### ISSUE TITLE
Example in help output on one line

### ISSUE THREAD

**Issue by Alber70g** [yargs/yargs#877]
Suggestion: put the examples on one line so that it can be easier copy/pasted. Right now, in the --help output, the example and the description of it, are in two columns. This hurts when a user wants to use the example that's given. It can also confuse the user since the parts of the command are not in one line. See below for an example:

```
$ node scripts/run-wct --help
Usage: node scripts/run-wct [options]

Options:
  --all, -a   Run all test suites (ignores + and - prefixes)           [boolean]
  --wct       Provide wct arguments                                     [string]
  --help, -h  Show help                                                [boolean]

Examples:
  node scripts/run-wct --all                Runs all test stuites, without
  --wct="--skip-selenium-install            installing selenium and keeps
  --persistent"                             browser open
```

**Comment by bcoe** [comment]
@Alber70g what if, when you provide only one line for the example, it expands to take up the entire row?

I forget if we already implemented this, I know e'd talked about it for another part of the layout.

**Comment by Alber70g** [comment]
@bcoe That would be nice, but it's still not less user-friendly since you cannot copy the command if there are more than one example.

**Comment by dogboydog** [comment]
👍  I think allowing for copy pasting would be great!
